### PR TITLE
Use a single wazuh-manager-worker StatefulSet

### PR DESCRIPTION
**Pull request by rjmoseley**
Previously, each wazuh-manager-worker was a separate StatefulSet, with a separate ConfigMap for each one (I believe due to the need to feed in a unique hostname to the config of each worker).  This PR switches to use a single StatefulSet which can be scaled to the required number of replicas (default 2).  Each replica is given its own PVC by kubernetes, and on boot the config of each worker replica is updated with the correct hostname (i.e. the pod name).  Tested on a GKE cluster and verified using `/var/ossec/bin/cluster_control -l`.  No reason why the number of workers couldn't be scaled further if required, simply edit the number of replicas of the StatefulSet

- Update the worker StatefulSet to use a single definition with 2 replicas by default
- Update the worker ConfigMap to take advantage of https://github.com/wazuh/wazuh-docker/pull/261
- Update the docs to reflect the above

Addresses some of the comments in https://github.com/wazuh/wazuh-kubernetes/issues/85.

### CODE REVIEW

**Review by JPLachance — APPROVED** [review]
This is how I deployed my workers in production and I confirm it works well!

**Comment by manuasir** [comment]
Thank you @rjmoseley ! I see some conflicts to be resolved, can you please take a look at it before it's merged?

**Comment by rjmoseley** [comment]
I'd branched before the most recent release, rebased now

**Review by manuasir — APPROVED** [review]
LGTM

**Pull request merged**
